### ISSUE TITLE
(1/1) FatalThrowableError

### ISSUE THREAD

**Issue by vishwakirtivardhan** [charlieuki/receipt-printer-example#9]
Class 'charlieuki\ReceiptPrinter\ReceiptPrinter' not found
<html>
<body>

in PrintController.php line 47
--

<br class="Apple-interchange-newline">

I am getting this error can you please help me out with this
</body>
</html>

**Comment by charlieuki** [comment]
Can you let me know which PHP version and Laravel version are you using?

**Comment by charlieuki** [comment]
> Class 'charlieuki\ReceiptPrinter\ReceiptPrinter' not found
> 
> ## in PrintController.php line 47
> 
> 
> I am getting this error can you please help me out with this

You might need to do `composer install` to install the dependencies, as I could not reproduce this issue on my local environment.

**Comment by vishwakirtivardhan** [comment]
@charlieuki I am using the PHP 7.2 and Laravel 7.2. 
**I am not able to install packet using composer. **

**Comment by charlieuki** [comment]
> @charlieuki I am using the PHP 7.2 and Laravel 7.2.
> **I am not able to install packet using composer. **

Can you post the entire error stack trace? Because I could not reproduce your issue as I can do `composer install` just fine on PHP 7.3 and Laravel 7.0.
